// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeTemplate.Data;

namespace PracticeTemplate.Migrations
{
    [DbContext(typeof(PracticeTemplateDBContext))]
    [Migration("20210415044031_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticeTemplate.Models.LoginUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("loginUsers");

                    b.HasData(
                        new { Id = 1, Password = "123", Username = "user1" },
                        new { Id = 2, Password = "123", Username = "user2" },
                        new { Id = 3, Password = "123", Username = "user3" },
                        new { Id = 4, Password = "123", Username = "user4" }
                    );
                });

            modelBuilder.Entity("PracticeTemplate.Models.SalaryTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Office");

                    b.Property<string>("Position");

                    b.Property<decimal>("Salary");

                    b.Property<DateTime>("Start");

                    b.HasKey("Id");

                    b.ToTable("salaryTables");

                    b.HasData(
                        new { Id = 1, Age = 61, Name = "Tiger Nixon", Office = "Edinburgh", Position = "System Architect", Salary = 320800m, Start = new DateTime(2011, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 2, Age = 61, Name = "Tiger Nixon", Office = "Edinburgh", Position = "System Architect", Salary = 0m, Start = new DateTime(2011, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 3, Age = 61, Name = "Tiger Nixon", Office = "Edinburgh", Position = "System Architect", Salary = 320800m, Start = new DateTime(2011, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 4, Age = 61, Name = "Tiger Nixon", Office = "Edinburgh", Position = "System Architect", Salary = 320800m, Start = new DateTime(2011, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
